### ISSUE TITLE
Clarification needed for ec2.conf

### ISSUE THREAD

**Issue by bcwilsondotcom** [saltstack-formulas/ec2-autoscale-reactor#11]
Need some clarification on the ec2.conf settings. 

```
my-ec2-config:
  id: <aws id>
  key: <aws key>
  keyname: <my key name>
  securitygroup: <my security group>
  private_key: </path/to/my/priv_key.pem>
  location: us-east-1
  provider: ec2
  minion:
    master: saltmaster.example.com
```

Is id the aws account id? the aws_access_key_id?
Is key is this the aws_access_key_id? the aws_secret_access_key?
What about keyname? securitygroup? and private_key?
